# lab04 multi variable linear regression


## 실습1

In [1]:
import tensorflow as tf

In [8]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 142.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')


In [9]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [10]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [11]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [14]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data,x2: x2_data,x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n",hy_val)

0 Cost: 3.8059742 
Prediction:
 [154.4352  181.66464 181.3662  195.75433 142.21964]
10 Cost: 3.7963862 
Prediction:
 [154.43141 181.66895 181.36584 195.75386 142.21938]
20 Cost: 3.7868474 
Prediction:
 [154.4276  181.67322 181.36554 195.75336 142.21909]
30 Cost: 3.777287 
Prediction:
 [154.42381 181.67752 181.36519 195.75288 142.21884]
40 Cost: 3.7678235 
Prediction:
 [154.42001 181.68176 181.36487 195.75237 142.21855]
50 Cost: 3.758305 
Prediction:
 [154.41623 181.68607 181.36455 195.7519  142.2183 ]
60 Cost: 3.7488747 
Prediction:
 [154.41246 181.69032 181.36423 195.75142 142.21803]
70 Cost: 3.7394645 
Prediction:
 [154.40868 181.69456 181.3639  195.75093 142.21777]
80 Cost: 3.7300408 
Prediction:
 [154.40489 181.6988  181.36354 195.75044 142.21748]
90 Cost: 3.7206597 
Prediction:
 [154.40112 181.70306 181.36324 195.74995 142.21722]
100 Cost: 3.7113633 
Prediction:
 [154.39738 181.70729 181.36293 195.74947 142.21698]
110 Cost: 3.702029 
Prediction:
 [154.39362 181.71152 181.3626  195

1220 Cost: 2.8133929 
Prediction:
 [154.00778 182.14651 181.32933 195.69943 142.18958]
1230 Cost: 2.8065903 
Prediction:
 [154.00458 182.15013 181.32907 195.69904 142.18936]
1240 Cost: 2.7997842 
Prediction:
 [154.00139 182.15376 181.3288  195.69862 142.18913]
1250 Cost: 2.7930171 
Prediction:
 [153.99817 182.15735 181.32852 195.6982  142.1889 ]
1260 Cost: 2.7862558 
Prediction:
 [153.99498 182.16095 181.32823 195.6978  142.18869]
1270 Cost: 2.7794726 
Prediction:
 [153.99178 182.16458 181.32797 195.6974  142.18846]
1280 Cost: 2.772766 
Prediction:
 [153.98859 182.16815 181.32768 195.69698 142.18822]
1290 Cost: 2.766053 
Prediction:
 [153.98541 182.17175 181.32741 195.69658 142.188  ]
1300 Cost: 2.7593465 
Prediction:
 [153.98221 182.17534 181.32713 195.69615 142.18779]
1310 Cost: 2.7527225 
Prediction:
 [153.97905 182.1789  181.32687 195.69574 142.18753]
1320 Cost: 2.746037 
Prediction:
 [153.97588 182.1825  181.3266  195.69536 142.18733]
1330 Cost: 2.7394032 
Prediction:
 [153.97269 

## 실습2

### using matrix

In [1]:
import tensorflow as tf

In [2]:
x_data = [[73., 80., 75.],[93., 88., 93.],
          [89., 91., 90.],[96., 98., 100.],[73., 66., 70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]


X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [3]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [4]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [5]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 500 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  51942.254 
Prediction:
 [[-52.863316]
 [-57.25903 ]
 [-59.734184]
 [-62.322258]
 [-44.681507]]
500 Cost:  2.9795926 
Prediction:
 [[149.45306]
 [185.72726]
 [179.78268]
 [198.4539 ]
 [140.65341]]
1000 Cost:  2.880814 
Prediction:
 [[149.54158]
 [185.67047]
 [179.81473]
 [198.43881]
 [140.61127]]
1500 Cost:  2.7920883 
Prediction:
 [[149.62086]
 [185.61995]
 [179.84389]
 [198.42204]
 [140.57692]]
2000 Cost:  2.7113812 
Prediction:
 [[149.69208]
 [185.57489]
 [179.8705 ]
 [198.4039 ]
 [140.54935]]


## 실습3

### loading data from file

In [62]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(42)

In [77]:
xy = np.loadtxt('./data/data-01-test-score.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape)
print(x_data, len(x_data))
print(y_data.shape)
print(y_data, len(y_data))

(6, 3)
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]] 6


In [64]:
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1], name = 'weight'))
b = tf.Variable(tf.random_normal([1], name = 'bias'))

In [65]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimiozer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [66]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [67]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict ={X : x_data, Y: y_data})
    if step % 500 == 0:
        print(step, "cost:", cost_val,'\nPrediction\n',hy_val)

0 cost: 9553.77 
Prediction
 [[58.677845]
 [73.79402 ]
 [70.905136]
 [79.59475 ]
 [54.97008 ]
 [44.24841 ]]
500 cost: 6.7646885 
Prediction
 [[150.60619]
 [183.96571]
 [179.63243]
 [197.89195]
 [139.00954]
 [105.99181]]
1000 cost: 6.3732753 
Prediction
 [[150.79178 ]
 [183.89221 ]
 [179.72142 ]
 [197.88617 ]
 [138.96416 ]
 [105.764565]]
1500 cost: 6.0405736 
Prediction
 [[150.94984 ]
 [183.8319  ]
 [179.79906 ]
 [197.87401 ]
 [138.93541 ]
 [105.564224]]
2000 cost: 5.7519417 
Prediction
 [[151.08461]
 [183.78265]
 [179.86703]
 [197.85658]
 [138.92055]
 [105.38682]]


In [68]:
print("Your score will be ", sess.run(hypothesis, feed_dict = {X: [[100, 70, 101]]}))
print("Other score will be ", sess.run(hypothesis, feed_dict = {X: [[60,70,110], [90, 100, 80]]}))

Your score will be  [[189.17007]]
Other score will be  [[189.3888 ]
 [170.58374]]


## 실습4

### Queue Runner


<img src="./images/queue_runner.png" width=45%/>

In [78]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(["1","2","3"],shuffle=False)
with tf.Session() as sess:
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord,sess=sess)

    for step in range(10):
        print(sess.run(filename_queue.dequeue()) )

    coord.request_stop()
    coord.join(threads)

b'1'
b'2'
b'3'
b'1'
b'2'
b'3'
b'1'
b'2'
b'3'
b'1'


## 실습5

### queue runner and batch

In [14]:
import tensorflow as tf

In [15]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [16]:
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)

In [17]:
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1], name = 'weight'))
b = tf.Variable(tf.random_normal([1], name = 'bias'))

In [18]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [19]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [20]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Field 0 in record 0 is not a valid float: # EXAM1
	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], field_delim=",", na_value="", select_cols=[], use_quote_delim=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0)]]
	 [[Node: DecodeCSV/_18 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_12_DecodeCSV", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


In [21]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

OutOfRangeError: FIFOQueue '_10_batch_2/fifo_queue' is closed and has insufficient elements (requested 10, current size 1)
	 [[Node: batch_2 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_2/fifo_queue, batch_2/n)]]

Caused by op 'batch_2', defined at:
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/asyncio/base_events.py", line 1425, in _run_once
    handle._run()
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2901, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-3e97b9057a5f>", line 3, in <module>
    train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 988, in batch
    name=name)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 762, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/data_flow_ops.py", line 476, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/pirl/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_10_batch_2/fifo_queue' is closed and has insufficient elements (requested 10, current size 1)
	 [[Node: batch_2 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_2/fifo_queue, batch_2/n)]]
