## MNIST

In [1]:
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_DATA/", one_hot = True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_DATA/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_DATA/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_DATA/t10k-images-idx3-ubyte.gz
Extracting MNIST_DATA/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [2]:
mnist

Datasets(train=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7f650d257e10>, validation=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7f650d2390d0>, test=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7f650d239110>)

In [3]:
import tensorflow as tf

nb_classes = 10
X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, nb_classes])
W = tf.Variable(tf.random_normal([784, nb_classes]))
b = tf.Variable(tf.random_normal([nb_classes]))

In [4]:
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

In [5]:
is_correct = tf.equal(tf.arg_max(hypothesis, 1), tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

Instructions for updating:
Use `argmax` instead


In [6]:
training_epochs = 15
batch_size = 100

sess = tf.Session()
sess.run(tf.global_variables_initializer())


In [7]:
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(mnist.train.num_examples/batch_size)   
    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        c, _ = sess.run([cost,optimizer], feed_dict = {X: batch_xs, Y : batch_ys})
        avg_cost += c / total_batch
    print("Epoch:", "%04d" % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))
print("Accuracy: ", accuracy.eval(session = sess, feed_dict = {X : mnist.test.images, Y: mnist.test.labels}))    

('Epoch:', '0001', 'cost =', '2.759746969')
('Epoch:', '0002', 'cost =', '1.077066833')
('Epoch:', '0003', 'cost =', '0.866801727')
('Epoch:', '0004', 'cost =', '0.761433929')
('Epoch:', '0005', 'cost =', '0.693852742')
('Epoch:', '0006', 'cost =', '0.645445314')
('Epoch:', '0007', 'cost =', '0.608296317')
('Epoch:', '0008', 'cost =', '0.579102744')
('Epoch:', '0009', 'cost =', '0.554875069')
('Epoch:', '0010', 'cost =', '0.534296186')
('Epoch:', '0011', 'cost =', '0.517171150')
('Epoch:', '0012', 'cost =', '0.501891065')
('Epoch:', '0013', 'cost =', '0.489219923')
('Epoch:', '0014', 'cost =', '0.477306939')
('Epoch:', '0015', 'cost =', '0.467067145')
('Accuracy: ', 0.88919997)


In [8]:
import matplotlib.pyplot as plt
import random
r = random.randint(0, mnist.test.num_examples - 1)
print("Label", sess.run(tf.argmax(mnist.test.labels[r:r+1], 1)))
print("prediction:", sess.run(tf.argmax(hypothesis, 1),
                                 feed_dict = {X:mnist.test.images[r:r+1]}))
plt.imshow(mnist.test.images[r:r+1].reshape(28,28),cmap="Greys",
              interpolation='nearest')
plt.show()

('Label', array([2]))
('prediction:', array([2]))


In [217]:
mnist.test.images[r:r+1]

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0. 

In [69]:
import os

import numpy as np

In [147]:
import scipy.ndimage

In [148]:
data = np.vectorize(lambda x: 255 - x)(np.ndarray.flatten(scipy.ndimage.imread("./tt_data/1.jpg", flatten=True)))

/home/pirl/anaconda3/envs/py35/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0.
Use ``matplotlib.pyplot.imread`` instead.
  """Entry point for launching an IPython kernel.


In [149]:
sess.run(tf.argmax(hypothesis, 1),feed_dict = {X:data})

ValueError: Cannot feed value of shape (425,) for Tensor u'Placeholder_3:0', which has shape '(?, 784)'

In [183]:
CHANNELS = 3 
IMAGE_SIZE = 28 
def tf_resize_images(X_img_file_paths): 
    X_data = [] 
    tf.reset_default_graph() 
    X = tf.placeholder(tf.float32, (None, None, CHANNELS)) 
    tf_img = tf.image.resize_images(X, (IMAGE_SIZE, IMAGE_SIZE), 
            tf.image.ResizeMethod.NEAREST_NEIGHBOR) 
    with tf.Session() as sess: 
        sess.run(tf.global_variables_initializer()) 

     # Each image is resized individually as different image may be of different size. 
        for index, file_path in enumerate(X_img_file_paths): 
            img = Image.open(file_path) 
            resized_img = sess.run(tf_img, feed_dict = {X: img}) 
            X_data.append(resized_img) 

    X_data = np.array(X_data, dtype = np.float32) # Convert to numpy 
    return X_data 

In [184]:

data_list = glob('tt_data/*.jpg')
data = tf_resize_images(data_list)

In [189]:
data.shape

(1450, 28, 28, 3)

In [192]:
data[0]

array([[[   0.,   13.,    0.],
        [   0.,   13.,    0.],
        [  20.,   19.,   14.],
        ..., 
        [  13.,    0.,   14.],
        [  13.,    0.,   14.],
        [   0.,    0.,    0.]],

       [[   0.,   13.,    0.],
        [   0.,   13.,    0.],
        [  20.,   19.,   14.],
        ..., 
        [  13.,    0.,   14.],
        [  13.,    0.,   14.],
        [   0.,    0.,    0.]],

       [[  22.,   17.,   11.],
        [  22.,   17.,   11.],
        [ 166.,  125.,  133.],
        ..., 
        [ 178.,  118.,  152.],
        [ 178.,  118.,  152.],
        [   0.,    0.,    0.]],

       ..., 
       [[  17.,    0.,    0.],
        [  17.,    0.,    0.],
        [ 184.,  121.,  140.],
        ..., 
        [ 213.,  123.,  158.],
        [ 213.,  123.,  158.],
        [   0.,    0.,    0.]],

       [[  22.,    3.,    5.],
        [  22.,    3.,    5.],
        [ 178.,  121.,  138.],
        ..., 
        [ 218.,  137.,  169.],
        [ 218.,  137.,  169.],
        [ 

In [218]:
data = tf.reshape(data, [-1, 28*28])


TypeError: Expected binary or unicode string, got <tf.Tensor 'Reshape_3:0' shape=(4350, 784) dtype=float32>

In [128]:


for file_path in enumerate(data_list):
    print(file_path)
    

(0, 'tt_data/485.jpg')
(1, 'tt_data/177.jpg')
(2, 'tt_data/198.jpg')
(3, 'tt_data/15.jpg')
(4, 'tt_data/708.jpg')
(5, 'tt_data/1322.jpg')
(6, 'tt_data/631.jpg')
(7, 'tt_data/1027.jpg')
(8, 'tt_data/118.jpg')
(9, 'tt_data/160.jpg')
(10, 'tt_data/218.jpg')
(11, 'tt_data/1355.jpg')
(12, 'tt_data/1010.jpg')
(13, 'tt_data/336.jpg')
(14, 'tt_data/1429.jpg')
(15, 'tt_data/817.jpg')
(16, 'tt_data/1156.jpg')
(17, 'tt_data/460.jpg')
(18, 'tt_data/1122.jpg')
(19, 'tt_data/1257.jpg')
(20, 'tt_data/1090.jpg')
(21, 'tt_data/208.jpg')
(22, 'tt_data/247.jpg')
(23, 'tt_data/166.jpg')
(24, 'tt_data/1220.jpg')
(25, 'tt_data/1041.jpg')
(26, 'tt_data/1142.jpg')
(27, 'tt_data/1337.jpg')
(28, 'tt_data/533.jpg')
(29, 'tt_data/1219.jpg')
(30, 'tt_data/139.jpg')
(31, 'tt_data/774.jpg')
(32, 'tt_data/684.jpg')
(33, 'tt_data/156.jpg')
(34, 'tt_data/518.jpg')
(35, 'tt_data/1015.jpg')
(36, 'tt_data/1334.jpg')
(37, 'tt_data/901.jpg')
(38, 'tt_data/1287.jpg')
(39, 'tt_data/285.jpg')
(40, 'tt_data/330.jpg')
(41, 'tt_d

In [62]:
from PIL import Image
import numpy as np

img = Image.open("6.png") 
img

<PIL.PngImagePlugin.PngImageFile image mode=P size=28x28 at 0x7F64F84E6050>

In [63]:
X_data = np.array(img, dtype = np.float32)

In [64]:
X_data

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  1.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  1.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  1.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  1.],
       [ 1

In [65]:
X_data.shape
X_data.resize([1,28*28])

In [66]:
X_data.shape

(1, 784)

In [12]:
X_data.shape
X_data = tf.reshape(X_data, [-1, 28*28])


In [16]:
X_data = np.array(X_data)
X_data

array(<tf.Tensor 'Reshape:0' shape=(1, 784) dtype=float32>, dtype=object)

In [18]:
sess.run(X_data)

TypeError: Fetch argument array(<tf.Tensor 'Reshape:0' shape=(1, 784) dtype=float32>, dtype=object) has invalid type <type 'numpy.ndarray'>, must be a string or Tensor. (Can not convert a ndarray into a Tensor or Operation.)

In [67]:
sess.run(tf.argmax(hypothesis, 1),feed_dict = {X:X_data})

array([6])

In [26]:
import scipy.ndimage
data = np.vectorize(lambda x: 255 - x)(np.ndarray.flatten(scipy.ndimage.imread("test.png", flatten=True)))

/home/pirl/anaconda3/envs/py35/lib/python2.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0.
Use ``matplotlib.pyplot.imread`` instead.
  


In [37]:
data = np.array(data).T
data = tf.reshape(data, [-1, 28*28])

TypeError: Expected binary or unicode string, got <tf.Tensor 'Reshape_1:0' shape=(1, 784) dtype=float64>

In [38]:
data

array(<tf.Tensor 'Reshape_1:0' shape=(1, 784) dtype=float64>, dtype=object)

In [57]:
ans = sess.run(tf.argmax(hypothesis, 1),feed_dict = {X:X_data})

In [58]:
print(ans)

[6]


In [105]:
from PIL import Image
import glob

test_data = list()
aa = sorted(glob.glob('./tt/*.png'))
for filename in aa:
    print(filename)
    tmp = Image.open(filename)
    img = tmp.copy()
    test_data.append(img)
   # tmp.close()

./tt/0001.png
./tt/0002.png
./tt/0003.png
./tt/0004.png
./tt/0005.png
./tt/0006.png
./tt/0007.png
./tt/0008.png
./tt/0009.png
./tt/0010.png
./tt/0011.png
./tt/0012.png
./tt/0013.png
./tt/0014.png
./tt/0015.png
./tt/0016.png
./tt/0017.png
./tt/0018.png
./tt/0019.png
./tt/0020.png
./tt/0021.png
./tt/0022.png
./tt/0023.png
./tt/0024.png
./tt/0025.png
./tt/0026.png
./tt/0027.png
./tt/0028.png
./tt/0029.png
./tt/0030.png
./tt/0031.png
./tt/0032.png
./tt/0033.png
./tt/0034.png
./tt/0035.png
./tt/0036.png
./tt/0037.png
./tt/0038.png
./tt/0039.png
./tt/0040.png
./tt/0041.png
./tt/0042.png
./tt/0043.png
./tt/0044.png
./tt/0045.png
./tt/0046.png
./tt/0047.png
./tt/0048.png
./tt/0049.png
./tt/0050.png
./tt/0051.png
./tt/0052.png
./tt/0053.png
./tt/0054.png
./tt/0055.png
./tt/0056.png
./tt/0057.png
./tt/0058.png
./tt/0059.png
./tt/0060.png
./tt/0061.png
./tt/0062.png
./tt/0063.png
./tt/0064.png
./tt/0065.png
./tt/0066.png
./tt/0067.png
./tt/0068.png
./tt/0069.png
./tt/0070.png
./tt/0071.png
./tt/0

./tt/0636.png
./tt/0637.png
./tt/0638.png
./tt/0639.png
./tt/0640.png
./tt/0641.png
./tt/0642.png
./tt/0643.png
./tt/0644.png
./tt/0645.png
./tt/0646.png
./tt/0647.png
./tt/0648.png
./tt/0649.png
./tt/0650.png
./tt/0651.png
./tt/0652.png
./tt/0653.png
./tt/0654.png
./tt/0655.png
./tt/0656.png
./tt/0657.png
./tt/0658.png
./tt/0659.png
./tt/0660.png
./tt/0661.png
./tt/0662.png
./tt/0663.png
./tt/0664.png
./tt/0665.png
./tt/0666.png
./tt/0667.png
./tt/0668.png
./tt/0669.png
./tt/0670.png
./tt/0671.png
./tt/0672.png
./tt/0673.png
./tt/0674.png
./tt/0675.png
./tt/0676.png
./tt/0677.png
./tt/0678.png
./tt/0679.png
./tt/0680.png
./tt/0681.png
./tt/0682.png
./tt/0683.png
./tt/0684.png
./tt/0685.png
./tt/0686.png
./tt/0687.png
./tt/0688.png
./tt/0689.png
./tt/0690.png
./tt/0691.png
./tt/0692.png
./tt/0693.png
./tt/0694.png
./tt/0695.png
./tt/0696.png
./tt/0697.png
./tt/0698.png
./tt/0699.png
./tt/0700.png
./tt/0701.png
./tt/0702.png
./tt/0703.png
./tt/0704.png
./tt/0705.png
./tt/0706.png
./tt/0

./tt/1297.png
./tt/1298.png
./tt/1299.png
./tt/1300.png
./tt/1301.png
./tt/1302.png
./tt/1303.png
./tt/1304.png
./tt/1305.png
./tt/1306.png
./tt/1307.png
./tt/1308.png
./tt/1309.png
./tt/1310.png
./tt/1311.png
./tt/1312.png
./tt/1313.png
./tt/1314.png
./tt/1315.png
./tt/1316.png
./tt/1317.png
./tt/1318.png
./tt/1319.png
./tt/1320.png
./tt/1321.png
./tt/1322.png
./tt/1323.png
./tt/1324.png
./tt/1325.png
./tt/1326.png
./tt/1327.png
./tt/1328.png
./tt/1329.png
./tt/1330.png
./tt/1331.png
./tt/1332.png
./tt/1333.png
./tt/1334.png
./tt/1335.png
./tt/1336.png
./tt/1337.png
./tt/1338.png
./tt/1339.png
./tt/1340.png
./tt/1341.png
./tt/1342.png
./tt/1343.png
./tt/1344.png
./tt/1345.png
./tt/1346.png
./tt/1347.png
./tt/1348.png
./tt/1349.png
./tt/1350.png
./tt/1351.png
./tt/1352.png
./tt/1353.png
./tt/1354.png
./tt/1355.png
./tt/1356.png
./tt/1357.png
./tt/1358.png
./tt/1359.png
./tt/1360.png
./tt/1361.png
./tt/1362.png
./tt/1363.png
./tt/1364.png
./tt/1365.png
./tt/1366.png
./tt/1367.png
./tt/1

In [97]:
aa[1]

'./tt/1272.png'

In [79]:
test_data.resize([-1,28*28])

AttributeError: 'list' object has no attribute 'resize'

In [101]:
import numpy as np
import shutil
ss = 0
for i in range(1450): 
    data = np.array(test_data[i], dtype = np.float32)
    data.resize([1,28*28])
    ans = sess.run(tf.argmax(hypothesis, 1),feed_dict = {X:data})
    print(aa[i])
    des = "./tt/"+str(int(ans))+"/"
    print(des)
    shutil.move(aa[i], des)
    print(ans)
    ss += ans
print(ss)


./tt/1245.png
./tt/8/
[8]
./tt/1272.png
./tt/7/
[7]
./tt/526.png
./tt/8/
[8]
./tt/381.png
./tt/7/
[7]
./tt/515.png
./tt/7/
[7]
./tt/1393.png
./tt/7/
[7]
./tt/812.png
./tt/7/
[7]
./tt/1047.png
./tt/8/
[8]
./tt/1174.png
./tt/7/
[7]
./tt/731.png
./tt/7/
[7]
./tt/718.png
./tt/7/
[7]
./tt/1059.png
./tt/7/
[7]
./tt/839.png
./tt/8/
[8]
./tt/447.png
./tt/7/
[7]
./tt/746.png
./tt/7/
[7]
./tt/717.png
./tt/7/
[7]
./tt/424.png
./tt/7/
[7]
./tt/262.png
./tt/8/
[8]
./tt/315.png
./tt/8/
[8]
./tt/187.png
./tt/7/
[7]
./tt/1173.png
./tt/7/
[7]
./tt/26.png
./tt/8/
[8]
./tt/1102.png
./tt/7/
[7]
./tt/1026.png
./tt/7/
[7]
./tt/790.png
./tt/7/
[7]
./tt/116.png
./tt/7/
[7]
./tt/1225.png
./tt/8/
[8]
./tt/176.png
./tt/7/
[7]
./tt/439.png
./tt/7/
[7]
./tt/1087.png
./tt/7/
[7]
./tt/94.png
./tt/8/
[8]
./tt/406.png
./tt/8/
[8]
./tt/70.png
./tt/6/
[6]
./tt/492.png
./tt/7/
[7]
./tt/296.png
./tt/7/
[7]
./tt/1106.png
./tt/7/
[7]
./tt/596.png
./tt/7/
[7]
./tt/352.png
./tt/7/
[7]
./tt/302.png
./tt/7/
[7]
./tt/224.png
./t

./tt/1096.png
./tt/7/
[7]
./tt/1358.png
./tt/7/
[7]
./tt/706.png
./tt/6/
[6]
./tt/1039.png
./tt/7/
[7]
./tt/345.png
./tt/8/
[8]
./tt/19.png
./tt/7/
[7]
./tt/75.png
./tt/7/
[7]
./tt/797.png
./tt/8/
[8]
./tt/852.png
./tt/7/
[7]
./tt/728.png
./tt/7/
[7]
./tt/692.png
./tt/8/
[8]
./tt/444.png
./tt/7/
[7]
./tt/1196.png
./tt/7/
[7]
./tt/564.png
./tt/6/
[6]
./tt/906.png
./tt/8/
[8]
./tt/440.png
./tt/7/
[7]
./tt/122.png
./tt/6/
[6]
./tt/931.png
./tt/6/
[6]
./tt/749.png
./tt/7/
[7]
./tt/277.png
./tt/7/
[7]
./tt/339.png
./tt/7/
[7]
./tt/662.png
./tt/6/
[6]
./tt/879.png
./tt/7/
[7]
./tt/157.png
./tt/7/
[7]
./tt/582.png
./tt/6/
[6]
./tt/11.png
./tt/7/
[7]
./tt/1277.png
./tt/6/
[6]
./tt/199.png
./tt/8/
[8]
./tt/970.png
./tt/7/
[7]
./tt/918.png
./tt/8/
[8]
./tt/1411.png
./tt/8/
[8]
./tt/490.png
./tt/6/
[6]
./tt/1027.png
./tt/7/
[7]
./tt/149.png
./tt/6/
[6]
./tt/1425.png
./tt/6/
[6]
./tt/1336.png
./tt/8/
[8]
./tt/872.png
./tt/7/
[7]
./tt/578.png
./tt/7/
[7]
./tt/992.png
./tt/5/
[5]
./tt/1046.png
./tt/

./tt/919.png
./tt/7/
[7]
./tt/1100.png
./tt/6/
[6]
./tt/544.png
./tt/6/
[6]
./tt/1440.png
./tt/6/
[6]
./tt/696.png
./tt/6/
[6]
./tt/844.png
./tt/7/
[7]
./tt/1110.png
./tt/7/
[7]
./tt/387.png
./tt/7/
[7]
./tt/822.png
./tt/6/
[6]
./tt/193.png
./tt/7/
[7]
./tt/903.png
./tt/7/
[7]
./tt/1378.png
./tt/7/
[7]
./tt/266.png
./tt/6/
[6]
./tt/494.png
./tt/7/
[7]
./tt/209.png
./tt/7/
[7]
./tt/405.png
./tt/7/
[7]
./tt/991.png
./tt/6/
[6]
./tt/780.png
./tt/7/
[7]
./tt/937.png
./tt/7/
[7]
./tt/411.png
./tt/7/
[7]
./tt/1331.png
./tt/7/
[7]
./tt/436.png
./tt/7/
[7]
./tt/1421.png
./tt/8/
[8]
./tt/1296.png
./tt/7/
[7]
./tt/359.png
./tt/8/
[8]
./tt/2.png
./tt/7/
[7]
./tt/716.png
./tt/8/
[8]
./tt/1070.png
./tt/7/
[7]
./tt/912.png
./tt/8/
[8]
./tt/869.png
./tt/5/
[5]
./tt/1401.png
./tt/7/
[7]
./tt/1132.png
./tt/7/
[7]
./tt/251.png
./tt/6/
[6]
./tt/1130.png
./tt/7/
[7]
./tt/1019.png
./tt/7/
[7]
./tt/881.png
./tt/7/
[7]
./tt/227.png
./tt/7/
[7]
./tt/1239.png
./tt/8/
[8]
./tt/756.png
./tt/7/
[7]
./tt/117.png
.

./tt/513.png
./tt/6/
[6]
./tt/944.png
./tt/3/
[3]
./tt/1166.png
./tt/7/
[7]
./tt/794.png
./tt/7/
[7]
./tt/1062.png
./tt/7/
[7]
./tt/297.png
./tt/6/
[6]
./tt/217.png
./tt/8/
[8]
./tt/599.png
./tt/8/
[8]
./tt/1213.png
./tt/7/
[7]
./tt/828.png
./tt/6/
[6]
./tt/464.png
./tt/7/
[7]
./tt/1074.png
./tt/6/
[6]
./tt/748.png
./tt/7/
[7]
./tt/225.png
./tt/6/
[6]
./tt/56.png
./tt/7/
[7]
./tt/668.png
./tt/8/
[8]
./tt/1056.png
./tt/7/
[7]
./tt/557.png
./tt/7/
[7]
./tt/1450.png
./tt/8/
[8]
./tt/434.png
./tt/7/
[7]
./tt/1279.png
./tt/7/
[7]
./tt/148.png
./tt/7/
[7]
./tt/380.png
./tt/8/
[8]
./tt/1053.png
./tt/6/
[6]
./tt/242.png
./tt/6/
[6]
./tt/197.png
./tt/7/
[7]
./tt/190.png
./tt/7/
[7]
./tt/34.png
./tt/7/
[7]
./tt/1168.png
./tt/7/
[7]
./tt/62.png
./tt/6/
[6]
./tt/1201.png
./tt/7/
[7]
./tt/479.png
./tt/6/
[6]
./tt/1138.png
./tt/8/
[8]
./tt/186.png
./tt/7/
[7]
./tt/1384.png
./tt/6/
[6]
./tt/640.png
./tt/7/
[7]
./tt/101.png
./tt/5/
[5]
./tt/1107.png
./tt/6/
[6]
./tt/1233.png
./tt/7/
[7]
./tt/1206.png


./tt/1202.png
./tt/6/
[6]
./tt/932.png
./tt/8/
[8]
./tt/343.png
./tt/5/
[5]
./tt/1364.png
./tt/6/
[6]
./tt/657.png
./tt/7/
[7]
./tt/638.png
./tt/7/
[7]
./tt/357.png
./tt/6/
[6]
./tt/356.png
./tt/5/
[5]
./tt/119.png
./tt/8/
[8]
./tt/1004.png
./tt/7/
[7]
./tt/680.png
./tt/2/
[2]
./tt/1251.png
./tt/6/
[6]
./tt/1248.png
./tt/7/
[7]
./tt/18.png
./tt/6/
[6]
./tt/106.png
./tt/8/
[8]
./tt/1136.png
./tt/6/
[6]
./tt/142.png
./tt/7/
[7]
./tt/826.png
./tt/7/
[7]
./tt/1447.png
./tt/8/
[8]
./tt/727.png
./tt/7/
[7]
./tt/613.png
./tt/7/
[7]
./tt/360.png
./tt/7/
[7]
./tt/375.png
./tt/8/
[8]
./tt/256.png
./tt/7/
[7]
./tt/485.png
./tt/6/
[6]
./tt/336.png
./tt/8/
[8]
./tt/408.png
./tt/7/
[7]
./tt/642.png
./tt/7/
[7]
./tt/602.png
./tt/6/
[6]
./tt/307.png
./tt/7/
[7]
./tt/705.png
./tt/6/
[6]
./tt/20.png
./tt/7/
[7]
./tt/443.png
./tt/8/
[8]
./tt/263.png
./tt/8/
[8]
./tt/497.png
./tt/7/
[7]
./tt/1430.png
./tt/8/
[8]
./tt/21.png
./tt/7/
[7]
./tt/1219.png
./tt/7/
[7]
./tt/489.png
./tt/6/
[6]
./tt/589.png
./tt/6

In [71]:
test_data

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,
         0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,
         0.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,
         1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
         0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0